// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	model "Test2/internal/user/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, u
func (_m *Repository) CreateUser(ctx context.Context, u model.CreateUser) (*model.User, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateUser) (*model.User, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateUser) *model.User); ok {
		r0 = rf(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateUser) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Repository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u model.CreateUser
func (_e *Repository_Expecter) CreateUser(ctx interface{}, u interface{}) *Repository_CreateUser_Call {
	return &Repository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *Repository_CreateUser_Call) Run(run func(ctx context.Context, u model.CreateUser)) *Repository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateUser))
	})
	return _c
}

func (_c *Repository_CreateUser_Call) Return(_a0 *model.User, _a1 error) *Repository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateUser_Call) RunAndReturn(run func(context.Context, model.CreateUser) (*model.User, error)) *Repository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *Repository) GetUser(ctx context.Context, id int64) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Repository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Repository_Expecter) GetUser(ctx interface{}, id interface{}) *Repository_GetUser_Call {
	return &Repository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *Repository_GetUser_Call) Run(run func(ctx context.Context, id int64)) *Repository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_GetUser_Call) Return(_a0 *model.User, _a1 error) *Repository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUser_Call) RunAndReturn(run func(context.Context, int64) (*model.User, error)) *Repository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByTgID provides a mock function with given fields: ctx, tgID
func (_m *Repository) GetUserByTgID(ctx context.Context, tgID int64) (*model.User, error) {
	ret := _m.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByTgID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.User, error)); ok {
		return rf(ctx, tgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.User); ok {
		r0 = rf(ctx, tgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, tgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserByTgID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTgID'
type Repository_GetUserByTgID_Call struct {
	*mock.Call
}

// GetUserByTgID is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID int64
func (_e *Repository_Expecter) GetUserByTgID(ctx interface{}, tgID interface{}) *Repository_GetUserByTgID_Call {
	return &Repository_GetUserByTgID_Call{Call: _e.mock.On("GetUserByTgID", ctx, tgID)}
}

func (_c *Repository_GetUserByTgID_Call) Run(run func(ctx context.Context, tgID int64)) *Repository_GetUserByTgID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_GetUserByTgID_Call) Return(_a0 *model.User, _a1 error) *Repository_GetUserByTgID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserByTgID_Call) RunAndReturn(run func(context.Context, int64) (*model.User, error)) *Repository_GetUserByTgID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx
func (_m *Repository) GetUsers(ctx context.Context) ([]model.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type Repository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) GetUsers(ctx interface{}) *Repository_GetUsers_Call {
	return &Repository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx)}
}

func (_c *Repository_GetUsers_Call) Run(run func(ctx context.Context)) *Repository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_GetUsers_Call) Return(_a0 []model.User, _a1 error) *Repository_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUsers_Call) RunAndReturn(run func(context.Context) ([]model.User, error)) *Repository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
