name: ci.yml
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Download depencies
        run: go mod download
      - name: Verify
        run: go mod verify
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race -coverprofile=converage.out -covermode=atomic ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
          fail_ci_if_error: false